{{ range .Values.postgres }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  nodeAffinity:
    {{- toYaml .nodeAffinity | nindent 4 }}
  tolerations: 
    {{- toYaml .tolerations | nindent 4 }}
  numberOfInstances: {{ .replicas }}
  {{- if .ressources.enabled }}
  resources:
    {{- omit .ressources "enabled" | toYaml | nindent 4 }}
  {{- end }}
  teamId: {{ .namespace }}
  schedulerName: stork
  masterServiceAnnotations:
      {{- toYaml .masterServiceAnnotations | nindent 4 }}
  replicaServiceAnnotations:
      {{- toYaml .replicaServiceAnnotations | nindent 4 }}
  postgresql:
    version: "14"
    parameters:
      password_encryption: scram-sha-256
      max_connections: "{{ .maxConnections }}"
      log_destination: "stderr"
      logging_collector: "false"
  volume:
    {{- toYaml .storage | nindent 4 }}
  preparedDatabases:
    {{- toYaml .preparedDatabases | nindent 4 }}
  nodeAffinity:
    {{- toYaml .nodeAffinity | nindent 4 }}
  tolerations:
    {{- toYaml .tolerations | nindent 4 }}
---
{{- end}}
