---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kor.serviceAccountName" . }}-read-resources-role-binding
  namespace: {{ .Values.cronJob.namespace }}
  labels:
    {{- include "kor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kor.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kor.serviceAccountName" . }}-read-resources-role
  apiGroup: rbac.authorization.k8s.io
