---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kor.serviceAccountName" . }}-read-resources-role
  namespace: {{ .Values.cronJob.namespace }}
  labels:
    {{- include "kor.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
