apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "oomkiller.fullname" . }}
  labels:
    {{- include "oomkiller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oomkiller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oomkiller.selectorLabels" . | nindent 8 }}
    spec:
      # We must mount the host pid namespace so that we have the ability to kill
      # processes inside other pods.
      hostPID: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oomkiller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
          - sh
          - -exc
          - |
            apk add earlyoom
            earlyoom -m {{ .Values.earlyoom.memory.sigtermPercent }},{{ .Values.earlyoom.memory.sigkillPercent }} {{ .Values.earlyoom.additionalArguments }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
