---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: barney-kafka-cluster
  namespace: {{ .Release.namespace }}
spec:
  kafka:
    replicas: {{ .Values.kafka.cluster.replicas }}
    {{- with .Values.kafka.cluster.resources }}
    resources: {{ toJson . }}
    {{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            annotations:
              getambassador.io/config: |
                ---
                apiVersion: getambassador.io/v2
                kind:  TCPMapping
                name:  barney_kafka_cluster_bootstrap_tcp_port_mapping
                ambassador_id:
                  - internal_proxy
                port: {{ .Values.kafka.cluster.service.tcp_port }}
                service: "barney-kafka-cluster-kafka-external-bootstrap.{{ $.Release.Namespace }}:9094"
    storage:
      type: ephemeral
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 3
      default.replication.factor: 3
      min.insync.replicas: 2
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    livenessProbe:
      timeoutSeconds: 20
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 3
    template:
      {{- with .Values.podDisruptionBudget }}
      podDisruptionBudget:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      pod:
        affinity:
          nodeAffinity:
            {{- toYaml .Values.nodeAffinity | nindent 12 }}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - barney-kafka-cluster-kafka
                  topologyKey: "kubernetes.io/hostname"
        tolerations:
          {{- toYaml .Values.tolerations | nindent 10 }}
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
  kafkaExporter:
    topicRegex: .*
    groupRegex: .*
    logging: debug
    enableSaramaLogging: true
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "9404"
        affinity:
          nodeAffinity:
            {{- toYaml .Values.nodeAffinity | nindent 12 }}
        tolerations:
          {{- toYaml .Values.tolerations | nindent 10 }}
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    {{- with .Values.zookeeper.resources }}
    resources: {{ toJson . }}
    {{- end }}
    storage:
      type: ephemeral
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    livenessProbe:
      timeoutSeconds: 20
      periodSeconds: 30
      failureThreshold: 3
    readinessProbe:
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 3
    template:
      {{- with .Values.podDisruptionBudget }}
      podDisruptionBudget:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      pod:
        affinity:
          nodeAffinity:
            {{- toYaml .Values.nodeAffinity | nindent 12 }}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - barney-kafka-cluster-zookeeper
                  topologyKey: "kubernetes.io/hostname"
        tolerations:
          {{- toYaml .Values.tolerations | nindent 10 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
