{{- range $secret, $values := $.Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: '{{ $secret }}'
  namespace: '{{ default $.Release.Namespace $values.namespace }}'
spec:
  {{- with $values.refreshInterval }}
  refreshInterval: '{{ . }}'
  {{- end }}
  secretStoreRef:
    name: 'eso-barney-clustersecretstore-{{ $.Release.Namespace }}'
    kind: ClusterSecretStore
  target:
    name: '{{ $secret }}'
    template:
      data:
        {{- toYaml (default dict $values.secret) | nindent 8 }}
  data:
  {{- toYaml (default dict $values.data) | nindent 2 }}
---
{{- end }}
