name: Generate helm chart on pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}
        path: main_HEAD

    - uses: actions/checkout@v4
      with:
        path: PR_HEAD

    - name: Generate helm chart for main_HEAD
      run: helm template main_HEAD/helm > main_HEAD_chart.yaml

    - name: Generate helm chart for PR_HEAD
      run: helm template PR_HEAD/helm > PR_HEAD_chart.yaml

    - name: Print the diff
      run: diff --unified=50 main_HEAD_chart.yaml PR_HEAD_chart.yaml || true
